export const syntheticEvaluationMetrics = {
  source: "Synthetic evaluation",
  denominator: 100,
  generated_at: null as string | null,
  exact_payment_order_matching_accuracy: 0.12,
  incident_classification_accuracy: 1,
  incident_classification_macro_f1: 1,
  automatic_count: 37,
  runbook_count: 37,
  no_action_count: 0,
  ambiguous_count: 63,
  afterstate_verification_coverage: 0,
  unsafe_recommendations: 0,
  unsafe_side_effects: 0,
  duplicate_action_prevention_count: null as number | null,
  operator_review_time_seconds: null as number | null,
  provider_integration_failures: null as number | null,
  merchant_integration_failures: null as number | null,
};
